

platform :ios, ‘8.0’


target "DBMDLiveShow" do


pod 'YYModel'
pod 'AFNetworking', '~> 3.0'


  # U-Share SDK UI模块（分享面板，建议添加）
    pod ‘UMengUShare/UI’

    # 集成新浪微博
    pod ‘UMengUShare/Social/Sina'



# 集成微信(完整版14.4M)
pod ‘UMengUShare/Social/WeChat'


    # 集成QQ
    pod ‘UMengUShare/Social/QQ'

pod "PLPlayerKit"
pod "PLMediaStreamingKit"
 pod 'RongCloudIMLib', '~> 2.7.3.1'

end
